  name: Delövning 1 - Minimal Pipeline
  
  on:
  # ska startas manuellt
    workflow_dispatch:
  
  jobs:
    print-info:
      runs-on: ubuntu-latest
      steps:
        - name: Start of pipeline
          run:  echo "Workflow starting"

        - name: python version
          run:  python --version