name: Delövning 4 - Triggers

on: 
  push: 
  pull_request:  
jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo info        
        run: echo "Workflow triggat av event:${{ github.event_name }}" 